### ISSUE TITLE
sharex not working

### ISSUE THREAD

**Issue by 3k2** [v0l/void.cat#13]
```
Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Request URL:
https://upload.void.cat/src/php/upload.php

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

**Comment by v0l** [comment]
Hi, thanks for opening this issue. I;ve renewed the SSL cert now.
