### ISSUE TITLE
System.IO.IOException: The operation is not allowed on non- connected sockets. 

### ISSUE THREAD

**Issue by metapea** [v0l/void.cat#21]
I tired uploading one of my files to Void (v0.2) but all i got was this:
`Unhandled Exception: System.IO.IOException: The operation is not allowed on non-
connected sockets.
   at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, B
oolean ownsSocket)
   at void_lib.Upload.UploadFileAsync(Stream in_stream, String filename, Byte[]
key, Byte[] iv) in C:\Users\username\Documents\GitHub\void.cat\tools\void_util\vo
id_lib\Upload.cs:line 78
   at void_util.Program.UploadFileAsync(String filename, Byte[] key, Byte[] iv)
in C:\Users\username\Documents\GitHub\void.cat\tools\void_util\void_util\Program.
cs:line 115
   at void_util.Program.<Main>(String[] args)
`

**Comment by metapea** [comment]
is it fix?
